### ISSUE TITLE
User interface elements for blackjack

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#7]
Messageboxes are okay but they are not perfect. When information is shown to the user, they can only see it while the message is open. After they close the message they either have to remember that information for the duration of the game or have the same information restated in every following message. 

We can supplement messages with new user interface HUD elements that only appear while playing the game. Below is some awful art I slapped together to show the kinds of info we might display on the HUD.

![ui_idea](https://cloud.githubusercontent.com/assets/1912967/26769096/296883e8-497a-11e7-8ac1-34a99e513a30.png)
![untitled](https://cloud.githubusercontent.com/assets/1912967/26620414/bdf8deb8-45b0-11e7-81e5-79eb434d05fc.png)

**Comment by TheWhiteCollarPlayers** [comment]
HUD elements would be ideal for the games. Here is my bulleted list of suggestions for them however.

- Remove the card elements from the HUD display, they are already laid out on the table so having them in the HUD seems a bit repetitive. Instead, maybe a simple total card value count?

- The amount wagered is perfect to put on the HUD, but again there seem to be two elements showing it, you could remove the blue dot since you already have the orange lettering. 

- Showing your caps inventory is fantastic as well for the HUD however I would simply rename it to Caps, also we will need to revisit it if we decide to use the wagering items from inventory. Perhaps you put everything you want to wager into a chest prior to starting the game and then that gets converted to "chips" which is the amount that show on the HUD?

- Lastly, not really important but a great HUD element for adding immersion to the game would be some sort of indicator of who's turn it is, maybe a little visual with highlighting seats?

**Comment by TheWhiteCollarPlayers** [comment]
Closing this as we have settled upon a great display for the game and the info is well represented to the player
