### ISSUE TITLE
Exiting a Blackjack game will put you in the wall sometimes.

### ISSUE THREAD

**Issue by Scrivener07** [Scrivener07/FO4_Games#90]
Depending on where the exit marker is during the exiting phase, you might end up stuck inside a wall. The NPC is the exit marker in the case of dialogue.
![screenshot38](https://user-images.githubusercontent.com/1912967/37183581-c34e04f6-2304-11e8-99df-a86bf73f7767.png)

**Comment by TheWhiteCollarPlayers** [comment]
As great as it would be to fix this, I have no idea how we would go about doing so. Not to mention this bug is pretty rare, would you want to consider labelling this a wontfix? Simply because there is not really a good way to fix this problem with the framework we have, but this problem can be prevented by the player.

**Comment by Scrivener07** [comment]
I haven't seen this happen more than once ever so maybe closing this for now would be okay. Though it doesnt seem appropriate to mark an issue with potential to break the game as something we "wont fix". We dont even fully know why this occurs in the first place. Im not ready to give up that easy. Closing for now seems okay. Just re-open this if it becomes a problem.
